export enum SOCKET_ENUMS {
  YOU_ARE_NEW_ADMIN = "YOU_ARE_NEW_ADMIN",
  NEW_PLAYER_LEAVE = "NEW_PLAYER_LEAVE",
  NEW_PLAYER_JOIN = "NEW_PLAYER_JOIN",
  ADMIN_DISMISS_YOU = "ADMIN_DISMISS_YOU",
  START_GAME = "START_GAME",
  GAME_MSG = "GAME_MSG"
}
